### ISSUE TITLE
Labeler is breaking our dont merge label to two seperate ones

### ISSUE THREAD

**Issue by riki-gertzik** [CodelyTV/pr-size-labeler#10]
when labeler is executing and pr has a "dont merge" label, the labeler is breaking it into two gray labels - "dont" and "merge"
Any idea why?

![image](https://user-images.githubusercontent.com/55353051/79132872-bb1bca00-7db3-11ea-8bff-925b9bd84dad.png)
(I changed to uppercase L)

Thanks in advance!

**Comment by gasigo** [comment]
I'm facing the same issue on my repository.

**Comment by riki-gertzik** [comment]
for now I fixed this issue by changing to `dont-merge` without spaces

**Comment by rgomezcasas** [comment]
During this week we'll fix it! :)

**Comment by gasigo** [comment]
Not sure if it's related to this bug, but now I can see that the label is not being added for every PR. If the PR contains a label with more than one word, the size label is never added.

**Comment by rgomezcasas** [comment]
Fixed in #11 and released overwriting the [v1 release](https://github.com/CodelyTV/pr-size-labeler/releases/tag/v1).

Can you verify it? :)

**Comment by gasigo** [comment]
It doesn't seem to add the tag anymore. I've opened a PR two hours ago.

**Comment by gasigo** [comment]
I meant it doesn't add the size tag anymore. But it also doesn't break the other tags.

**Comment by rgomezcasas** [comment]
Could you try again?

**Comment by gasigo** [comment]
Just tested it again, seems to be working now.

**Comment by rgomezcasas** [comment]
Cool!

Have a nice coding!! 😊
