### ISSUE TITLE
Error editing the issue

### ISSUE THREAD

**Issue by AlbertHernandez** [CodelyTV/pr-size-labeler#16]
After to configure the action I realize some times I have this error:

<img width="677" alt="Captura de pantalla 2020-05-05 a las 12 10 55" src="https://user-images.githubusercontent.com/29106063/81055714-8b9b4180-8ec9-11ea-8e2d-ee62b406c376.png">

I don't know why some times this is working well and other no, I didn't find any difference between PRs

**Comment by rgomezcasas** [comment]
This should be fixed now! Thanks!
