### ISSUE TITLE
Optional parameters and message

### ISSUE THREAD

**Issue by JavierMeep** [CodelyTV/pr-size-labeler#18]
Is it the message optional? Should be great it can be optional and avoid add a comment on every push to the PR branch, I think one comment is enough.

**Comment by JavierCane** [comment]
Hi!

* Yes, [you can customize the "PR too big" message](https://github.com/CodelyTV/pr-size-labeler/blob/master/README.md#L43)
* Regarding the number of comments to publish, we're discussing it on the issue https://github.com/CodelyTV/pr-size-labeler/issues/19. It would be great to take your feedback into account on how you expect it to behave. Thanks! 🙂

**Comment by rsstiglitz** [comment]
But how can you disable the message completely?
