### ISSUE TITLE
[Bug]: Inconsistent license file

### ISSUE THREAD

**Issue by rjlopezdev** [CodelyTV/pr-size-labeler#2]
`README.md` shows:

# License ⚖️ 
[MIT]()

But [LICENSE](https://github.com/CodelyTV/pr-size-labeler/blob/master/LICENSE) file is `Apache License 2.0`

Nice action 😄 💚 !

**Comment by JavierCane** [comment]
Thanks for reporting this issue @rjlopezdev !

[Fixed](https://github.com/CodelyTV/pr-size-labeler/commit/f2fed95b5cb2a9d798e9e21640179ab978a3dffe) 🎉
