### ISSUE TITLE
Liveness probe of repo

### ISSUE THREAD

**Issue by dominikmeyersap** [CodelyTV/pr-size-labeler#21]
https://github.com/CodelyTV/pr-size-labeler/blob/417e60a06bd915dd3d96ec4aa105f7d753a8f974/src/github.sh#L3
This renders the action useless for Github Enterprise users.

Are you around and would accept a PR?

**Comment by rgomezcasas** [comment]
Sure! ✌️

**Comment by dominikmeyersap** [comment]
Holi shit, fastest answer. Alright, ON IT!

**Comment by dominikmeyersap** [comment]
I will also make a small contribution to the docs. What is size: 1000? 1000 Additions or Deletions? If I am not mistaken this is LOC right?

**Comment by dominikmeyersap** [comment]
Replaced by https://github.com/CodelyTV/pr-size-labeler/pull/22
