### ISSUE TITLE
Github API url is not necessary

### ISSUE THREAD

**Issue by erodewald** [CodelyTV/pr-size-labeler#27]
By default, GitHub and its variants include an [`GITHUB_API_URL` environment variable](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables), so the addition of `github_api_url` just increased code complexity, reduced maintainability, and actually reduced flexibility since it assumes `https://`. The latter meant I was not able to simply pass in `$GITHUB_API_URL`, because it became an invalid url (e.g., `https://https://my-enterprise.url.com/api/v3`).

**Comment by cscleison** [comment]
actually, if i keep the `github_api_url: 'api.github.com'` that is in example, it does not label my prs at all. it only worked after i omitted the line. it took me quite a while to figure it out 😄

**Comment by rubeeengm** [comment]
> By default, GitHub and its variants include an [`GITHUB_API_URL` environment variable](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables), so the addition of `github_api_url` just increased code complexity, reduced maintainability, and actually reduced flexibility since it assumes `https://`. The latter meant I was not able to simply pass in `$GITHUB_API_URL`, because it became an invalid url (e.g., `https://https://my-enterprise.url.com/api/v3`).

Nice

**Comment by rubeeengm** [comment]
> actually, if i keep the `github_api_url: 'api.github.com'` that comes from the example, it does not label my prs at all. it only worked after i omitted the line. it took me quite a while to figure it out 😄

Nice!

**Comment by johnlk** [comment]
There were two potential issues:
1. the readme example excluded the `http://` which would break if copied
2. github enterprise accounts have to set a value, which shouldn't be required

Both have seen been addressed by #57 and #62 respectively.
