### ISSUE TITLE
Ability to set label color

### ISSUE THREAD

**Issue by tzieleniewski** [CodelyTV/pr-size-labeler#31]
Howdy,

I would be nice to have an ability to set a custom label color.
Could be either for all labels as one option or per each.

All the best

**Comment by JavierCane** [comment]
Hi @tzieleniewski!

By the moment we would suggest to edit it through the GitHub interface. You can do so following the next steps:

1. Go to `https://github.com/$organization/$repository/labels`
2. Select the label you want to customize: ![pr-size-labeler 2021-09-22 15-30-51](https://user-images.githubusercontent.com/986235/134353253-d588f301-4e9b-451e-a1d5-7169e4390ad6.png)
3. Set the color you prefer: ![pr-size-labeler 2021-09-22 15-30-10](https://user-images.githubusercontent.com/986235/134352853-48e8de1b-3367-46cc-bc5a-f4ada176051b.png)

Here you have the color codes we use:

- `xs`: `#bfdadc`
- `s`: `#c2e0c6`
- `m`: `#fef2c0`
- `l`: `#f9d0c4`
- `xl`: `#e99695`
