### ISSUE TITLE
Ignore files and folders by pattern?

### ISSUE THREAD

**Issue by billxinli** [CodelyTV/pr-size-labeler#38]
Is it possible to ignore files and folders by patterns?

For example, ignoring snapshots directories, ignoring JSON fixtures directories, ignoring some test folders.

Sometimes a change may be a few lines of code, however, the test itself could generate more than the limits defined.

**Comment by billxinli** [comment]
Oh interesting. Thank for you looking into this. I think this should be easily added. I might take a stab at this.

**Comment by morey-tech** [comment]
I was looking into what it might take to convert that to a globing match. Seems like [`compgen` is an efficient solution for that](https://stackoverflow.com/a/34195247). 

We would need to implement a backwards-compatible solution, something where we default to matching a filename at the end of the path (so any parent directory) and also support more complex patterns. Maybe introduce a new input `patterns_to_ignore`?

**Comment by mediamartin** [comment]
@morey-tech wanted to also use a pattern to ignore so came into this topic. A separate input like `patterns_to_ignore` would be great!

**Comment by alecmerdler** [comment]
Would love to see this feature implemented. For our project that relies heavily on OpenAPI code generation, every pull request is being flagged.

**Comment by wu-cl** [comment]
#50 Here is a solution for this feather,  are there someone could review this patch?

**Comment by wu-cl** [comment]
@rgomezcasas
