### ISSUE TITLE
Is it possible to make github bot as labeler?

### ISSUE THREAD

**Issue by seewoo5** [CodelyTV/pr-size-labeler#42]
I'm using the labeler to my company's code, and it is very useful.
By the way, when PR is made, the user who added this github action to workflow is working as labeler.
I wonder if it is possible to add github bot and assign it as a labeler, so that the other user may not be involved in the PR.

**Comment by dbelyaev** [comment]
Not sure what is your configuration, but in my repository (enterprise owned repo) it is done as bot:
![image](https://github.com/CodelyTV/pr-size-labeler/assets/6915328/97e1d570-b422-4984-a540-ef905525c401)

**Comment by johnlk** [comment]
Same for me. Perhaps a stale issue. Going to close:
<img width="677" alt="image" src="https://github.com/CodelyTV/pr-size-labeler/assets/8771036/2d05aa17-fdb5-4edf-89ad-2ae37d27f07c">
