### ISSUE TITLE
XL warning message is posted repeatedly

### ISSUE THREAD

**Issue by EngJay** [CodelyTV/pr-size-labeler#48]
Each time the workflow runs, another instance of the XL warning messages is posted to the PR.

![image](https://user-images.githubusercontent.com/32394923/202532025-e64c4439-0a3f-4ae5-b368-bb1e94db075d.png)

**Comment by EngJay** [comment]
I also suspect that if the size of the PR falls below the XL threshold, the warning is not removed.

**Comment by adrianjost** [comment]
duplicate of https://github.com/CodelyTV/pr-size-labeler/issues/19
