### ISSUE TITLE
A new release with regex support

### ISSUE THREAD

**Issue by dbelyaev** [CodelyTV/pr-size-labeler#54]
Please, release a new version **v1.8.2** that includes [d269449310fe33526c56b2dfe6244e3a9f489b15](https://github.com/CodelyTV/pr-size-labeler/commit/d269449310fe33526c56b2dfe6244e3a9f489b15) available in `main`.

**Comment by trohovsky-mhp** [comment]
You can use it as `-   uses: codelytv/pr-size-labeler@d269449310fe33526c56b2dfe6244e3a9f489b15` until it is release.

**Comment by elijaholmos** [comment]
@rgomezcasas can we get this officially released & tagged, please?

**Comment by dbelyaev** [comment]
Closing as it has been released as a part of https://github.com/CodelyTV/pr-size-labeler/releases/tag/v1.9.0 release.
