### ISSUE TITLE
Is it possible to ignore line count from deleted files?

### ISSUE THREAD

**Issue by OnkarRuikar** [CodelyTV/pr-size-labeler#66]
Thank you for the such an useful tool!

We have implemented it in `mdn/content`. In [this PR](https://github.com/mdn/content/pull/31878) only files were deleted, we use a custom command to deletions so there was almost no effort reviewing the PR.

But the PR got the biggest size label `size/xl`. Is is possible to ignore lines from deleted files?

**Comment by johnlk** [comment]
Love this idea! Agreed. At least providing an option like `ignore_deletions: false` which is false by default

**Comment by johnlk** [comment]
Addressed in #76 🤞🏻
