### ISSUE TITLE
files_to_ignore

### ISSUE THREAD

**Issue by scottbert** [CodelyTV/pr-size-labeler#67]
So I'm not sure if this is a bug or this is me just not understanding how to work the yaml file but...

I have a codebase I just pushed a small PR to and it got flagged as being over 1000 lines by the pr-size-labeler

Code changes: 5 files, 235 lines
Snapshot changes: 3 files, 2358 lines

The labeler *should* be ignoring the snapshot files but doesn't appear to be.

I've tried both styles of config:

```yaml
files_to_ignore: "*.snap *.lock"
```
and 
```yaml
files_to_ignore: |
  "*.snap"
  "*.lock"
```

Is it something I'm doing incorrectly? Would it have an issue with deeply nested filenames? EG:
```/components/Footer/__snapshots__/index.test.tsx.snap```

Sorry for the noise if I'm doing something wrong!

**Comment by SimonSchick** [comment]
Running into the same issue, this functionality seems somewhat broken.

**Comment by Tuizi** [comment]
Yes the fix for that has never been released. I believe this repository is not maintained anymore

**Comment by johnlk** [comment]
#71 may have corrected this problem. The config value needed to be expanded as a whitespace separated list, done here https://github.com/CodelyTV/pr-size-labeler/pull/71/files#diff-d7c80f5e143a779b6ea480fe7455d4ba2934ccd1b453062355c72f000c9e7d02R15

Now the action logic matches the unit tests. I'll keep an eye on this issue, but after issuing a new release, this _should_ be solved
